### 사용자 주소 등록
POST http://localhost:8083/api/shop/members/address
Content-Type: application/json
X-USER-ID: kim123456

{
  "addressAlias": "집",
  "addressDetail": "1층 집",
  "addressRoadname": "청주시 서원구 구룡산로 417번길 104",
  "addressPostalNumber": "54321"
}

### 사용자 주소 전체 조회
GET http://localhost:8083/api/shop/members/address
Content-Type: application/json
X-USER-ID: kim123456

### 사용자 주소 삭제 (1번 삭제)
DELETE http://localhost:8083/api/shop/members/address/1
Content-Type: application/json
