### 최상위 카테고리 생성 - 국내도서
POST http://localhost:8080/api/category

{
  "categoryName": "국내도서",
  "categoryIsUsed": true,
  "superCategoryId": null
}

### 최상위 카테고리 생성 - 해외도서
POST http://localhost:8080/api/category

{
  "categoryName": "해외도서",
  "categoryIsUsed": true,
  "superCategoryId": null
}

### 국내도서 하위 카테고리 생성 - 문학
POST http://localhost:8080/api/category

{
  "categoryName": "문학",
  "categoryIsUsed": true,
  "superCategoryId": 1
}

### 국내도서 하위 카테고리 생성 - 에세이
POST http://localhost:8080/api/category

{
  "categoryName": "에세이",
  "categoryIsUsed": true,
  "superCategoryId": 1
}

### 문학 하위 카테고리 생성 - 시
POST http://localhost:8080/api/category


{
  "categoryName": "시",
  "categoryIsUsed": true,
  "superCategoryId": 3
}

### 문학 하위 카테고리 생성 - 소설
POST http://localhost:8080/api/category

{
  "categoryName": "소설",
  "categoryIsUsed": true,
  "superCategoryId": 3
}

### 전체 카테고리 트리 조회
GET http://localhost:8080/api/category


### 특정 ID를 가진 카테고리 조회 (예: 국내도서 ID가 1인 경우)
GET http://localhost:8080/api/category/1


### 특정 카테고리의 자식 카테고리 조회 (예: 문학 ID가 3인 경우)
GET http://localhost:8080/api/category/3/children


### 특정 카테고리의 최상위 경로 조회 (예: 시 ID가 5인 경우)
GET http://localhost:8080/api/category/5/path


### 카테고리 이름으로 검색 (예: 소설)
GET http://localhost:8080/api/category/search?name=소설


### 특정 카테고리 업데이트 (예: 에세이 ID가 4인 경우)
PUT http://localhost:8080/api/category/4

{
  "categoryName": "자기계발",
  "categoryIsUsed": true,
  "superCategoryId": 1
}


### 특정 카테고리 소프트 삭제 (예: 소설 ID가 6인 경우)
DELETE http://localhost:8080/api/category/6

