###회원 생성
POST http://localhost:8080/api/members
Content-Type: application/json

{
  "loginId": "kim",
  "loginPassword": "test1234",
  "customerName" : "mang mang 2",
  "customerPhoneNumber" : "010-3622-0514",
  "customerEmail" : "xxx@naver.com",
  "birth" : "19990514"
}

