###회원 생성
POST http://localhost:8083/api/shop/members
Content-Type: application/json

{
  "loginId": "kim123456",
  "loginPassword": "test1234",
  "customerName" : "김희망",
  "customerPhoneNumber" : "010-3622-0514",
  "customerEmail" : "xxx@naver.com",
  "birth" : "19990514"
}

### 8개 필요
### member_grade_id
### customerName -> customer
### customerPhone -> customer
### customerEmail -> customer
### birth
### 자동? created at, status, point
